'use client'
import React from 'react';
import SwaggerUI from 'swagger-ui-react';
import 'swagger-ui-react/swagger-ui.css';
// import the json file generated by the swagger-jsdoc
import swaggerFile from './api_spec.json';

const SwaggerPage = () => {
  return (
    <div>
      <h1>API Documentation</h1>
      <SwaggerUI spec={swaggerFile} />
    </div>
  );
};

export default SwaggerPage;
